/* TraceFlow / Vector Atelier: landing asimétrica, editorial y centrada en la transformación visual. */
import { ArrowRight, Check, Eraser, Layers3, ScanLine, WandSparkles } from 'lucide-react';
import { Link } from 'wouter';
import TraceFlowShell from '@/components/TraceFlowShell';
import hero from '@/assets/hero-illustration.svg';
import sample from '@/assets/sample-transform.svg';

export default function Home() {
  return <TraceFlowShell>
    <main>
      <section className="container relative grid min-h-[650px] items-center gap-12 overflow-hidden py-20 lg:grid-cols-[.9fr_1.1fr] lg:py-24">
        <div className="pointer-events-none absolute -left-16 top-16 h-56 w-56 rounded-full bg-[#22C7E8]/10 blur-3xl" />
        <div className="relative z-10 max-w-[620px] reveal"><div className="eyebrow mb-6 flex items-center gap-3"><span className="h-px w-8 bg-[#1687F8]" /> Procesamiento inteligente de imágenes</div><h1 className="font-display text-5xl font-semibold leading-[.98] tracking-[-0.065em] text-[#101A46] sm:text-7xl">De píxeles sueltos a <span className="text-[#1687F8]">curvas</span> que puedes usar.</h1><p className="mt-7 max-w-[500px] text-lg leading-relaxed text-[#626c86]">Convierte imágenes raster en SVGs limpios y elimina fondos con un flujo rápido, preciso y pensado para resultados profesionales.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/workspace" className="button-press inline-flex items-center justify-center gap-2 rounded-xl bg-[#1687F8] px-5 py-3.5 text-sm font-bold text-white shadow-[0_12px_22px_rgba(22,135,248,.2)] hover:bg-[#0e74dd]">Probar vectorizador <ArrowRight size={16} /></Link><Link href="/background-remover" className="button-press inline-flex items-center justify-center gap-2 rounded-xl border border-[#cfd5e1] bg-white px-5 py-3.5 text-sm font-bold text-[#101A46] hover:border-[#1687F8]">Quitar un fondo</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs font-semibold text-[#7a8299]"><span className="flex items-center gap-2"><Check size={14} className="text-[#1687F8]" /> Salida lista para SVG</span><span className="flex items-center gap-2"><Check size={14} className="text-[#1687F8]" /> PNG transparente</span><span className="flex items-center gap-2"><Check size={14} className="text-[#1687F8]" /> Sin conocimientos avanzados</span></div></div>
        <div className="relative reveal reveal-delay-1"><div className="absolute -inset-6 rounded-[2rem] bg-[#1687F8]/5 blur-2xl" /><div className="relative overflow-hidden rounded-[2rem] border border-[#dfe2ea] bg-white p-3 shadow-[0_24px_70px_rgba(16,26,70,.12)]"><img src={hero} alt="Trazos Bézier y píxeles transformándose en el flujo de TraceFlow" className="h-[330px] w-full rounded-[1.35rem] object-cover sm:h-[420px]" /><div className="absolute bottom-8 left-8 right-8 flex items-center justify-between rounded-xl border border-white/70 bg-white/90 px-4 py-3 shadow-lg backdrop-blur"><div><div className="eyebrow">Motor vectorial</div><div className="mt-1 text-sm font-bold text-[#101A46]">Trazos limpios, menos nodos</div></div><div className="flex gap-1.5"><span className="h-2 w-2 rounded-full bg-[#101A46]" /><span className="h-2 w-2 rounded-full bg-[#1687F8]" /><span className="h-2 w-2 rounded-full bg-[#22C7E8]" /></div></div></div><div className="absolute -right-4 -top-6 hidden h-20 w-20 rounded-2xl border border-[#dfe2ea] bg-[#fbfbf8] p-4 shadow-lg sm:block"><div className="grid grid-cols-3 gap-1.5">{Array.from({ length: 9 }).map((_, i) => <span key={i} className={`aspect-square rounded-[2px] ${i % 3 === 0 ? 'bg-[#1687F8]' : i % 4 === 0 ? 'bg-[#7C3AED]' : 'bg-[#101A46]'}`} />)}</div></div></div>
      </section>

      <section id="features" className="border-y border-[#dfe2ea] bg-[#f5f5f1] py-20"><div className="container"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><div className="eyebrow">Un estudio, dos flujos</div><h2 className="mt-4 font-display text-4xl font-semibold tracking-[-.05em] text-[#101A46]">La herramienta que entiende lo que quieres conservar.</h2></div><div className="grid gap-4 sm:grid-cols-2"><Link href="/workspace" className="group rounded-2xl border border-[#dfe2ea] bg-white p-6 transition-all hover:-translate-y-1 hover:border-[#1687F8] hover:shadow-[0_15px_30px_rgba(16,26,70,.08)]"><div className="mb-12 flex items-center justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e8f5ff] text-[#1687F8]"><WandSparkles size={20} /></span><ArrowRight size={18} className="text-[#a4abc0] transition-transform group-hover:translate-x-1 group-hover:text-[#1687F8]" /></div><h3 className="font-display text-xl font-semibold text-[#101A46]">Vectorizar raster</h3><p className="mt-2 text-sm leading-relaxed text-[#69728a]">Convierte logos, ilustraciones y capturas en SVGs editables con menos nodos y más fidelidad.</p></Link><Link href="/background-remover" className="group rounded-2xl border border-[#dfe2ea] bg-white p-6 transition-all hover:-translate-y-1 hover:border-[#22C7E8] hover:shadow-[0_15px_30px_rgba(16,26,70,.08)]"><div className="mb-12 flex items-center justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e7fbfc] text-[#0d9fb4]"><Eraser size={20} /></span><ArrowRight size={18} className="text-[#a4abc0] transition-transform group-hover:translate-x-1 group-hover:text-[#0d9fb4]" /></div><h3 className="font-display text-xl font-semibold text-[#101A46]">Quitar fondo</h3><p className="mt-2 text-sm leading-relaxed text-[#69728a]">Aísla el sujeto principal con bordes limpios y exporta imágenes listas para componer.</p></Link></div></div></div></section>

      <section id="how-it-works" className="container py-24"><div className="grid items-center gap-14 lg:grid-cols-[1fr_1.1fr]"><div><div className="eyebrow">Cómo funciona</div><h2 className="mt-4 max-w-[460px] font-display text-4xl font-semibold leading-tight tracking-[-.05em] text-[#101A46]">Un proceso visible de principio a fin.</h2><p className="mt-5 max-w-[440px] leading-relaxed text-[#69728a]">Cada paso queda claro: carga, ajusta, revisa y exporta. Sin cajas negras ni controles escondidos.</p><div className="mt-8 space-y-5">{[['01','Carga tu fuente','PNG, JPG, WEBP o SVG.'],['02','Ajusta el trazado','Ajusta detalle, suavizado y color.'],['03','Exporta el resultado','Descarga un asset limpio para tu próxima pantalla.']].map(([n,t,d]) => <div className="flex gap-4" key={n}><span className="font-display text-sm font-bold text-[#1687F8]">{n}</span><div><h3 className="font-bold text-[#101A46]">{t}</h3><p className="mt-1 text-sm text-[#7a8299]">{d}</p></div></div>)}</div></div><div className="relative overflow-hidden rounded-[2rem] border border-[#dfe2ea] bg-[#f4f4f0] p-4"><img src={sample} alt="Ejemplo conceptual de transformación de píxeles a vector" className="h-[300px] w-full rounded-2xl object-cover" /><div className="absolute left-9 top-9 rounded-full bg-white/90 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.15em] text-[#101A46] shadow-sm">Antes → después</div></div></div></section>

      <section className="container pb-24"><div className="relative overflow-hidden rounded-[2rem] bg-[#101A46] px-7 py-12 text-white sm:px-12"><div className="absolute -right-10 -top-24 h-72 w-72 rounded-full border-[32px] border-[#1687F8]/20" /><div className="relative max-w-[560px]"><div className="eyebrow text-[#5fdcf1]">Listo cuando tú quieras</div><h2 className="mt-4 font-display text-4xl font-semibold tracking-[-.05em]">Haz que tu próximo asset fluya.</h2><p className="mt-4 max-w-[470px] leading-relaxed text-white/65">Empieza con una imagen. Sal con un resultado más limpio, más ligero y listo para producción.</p><Link href="/workspace" className="button-press mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3.5 text-sm font-bold text-[#101A46] hover:bg-[#e8f5ff]">Abrir TraceFlow <ArrowRight size={16} /></Link></div></div></section>
    </main>
  </TraceFlowShell>;
}
